version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  postgres:
    image: library/postgres:13.2-alpine
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  app:
    container_name: oishiiGohan
    build: ./app
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./app:/app
      - gems:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
volumes:
  gems:
  node_modules:
